version: '3.3'
services:
  my-redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data
      - ./redis.conf:/etc/redis/redis.conf
      - ./logs:/logs
    #配置文件启动
    command: redis-server /etc/redis/redis.conf

