version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      - JAVA_OPTS=-Duser.timezone=Asia/Shanghai
    user: root
    privileged: true
    networks:
      - my_network # 将数据库服务连接到自定义网络

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16 # 指定一个合适的子网
