version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123 # 设置 root 用户密码
      MYSQL_DATABASE: master # 初始化时创建的数据库
      MYSQL_USER: master # 创建的数据库用户
      MYSQL_PASSWORD: 123 # 数据库用户的密码
    ports:
      - "13306:3306" # 映射 MySQL 端口
      - "13060:33060" # X Plugin 默认端口（重要！）  
    volumes:
      - ./mysql_data:/var/lib/mysql # 持久化数据到本地
    networks:
      - my_network # 将数据库服务连接到自定义网络

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16 # 指定一个合适的子网

