version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - prometheus-net

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    ports:
      - "9091:9091"
    command:
      - '--web.listen-address=:9091'
      - '--web.telemetry-path=/metrics'
      - '--persistence.file=/pushgateway/data/file'
      - '--persistence.interval=5m'
    volumes:
      - pushgateway_data:/pushgateway/data
    restart: unless-stopped
    networks:
      - prometheus-net

volumes:
  prometheus_data:
  pushgateway_data:

networks:
  prometheus-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/16 # 指定一个合适的子网