global:
  scrape_interval: 15s
  evaluation_interval: 15s

# 告警规则配置
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# 抓取配置
scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Pushgateway 监控
  - job_name: 'pushgateway'
    honor_labels: true  # 重要：保留推送的标签
    static_configs:
      - targets: ['pushgateway:9091']
    scrape_interval: 5s

  # 你的应用监控（如果用拉取模式）
  - job_name: 'my_app'
    static_configs:
      - targets: ['host.docker.internal:8080']  # 如果应用运行在宿主机
    scrape_interval: 10s