{
 "title": "process-monitor",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(system_memory_usage_percent,job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(system_memory_usage_percent,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "system load average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "system_load_average{job=~\"$job\", instance=~\"$instance\", period=\"1m\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "system cpu usage percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_cpu_usage_percent{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "system mem usage percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_memory_usage_percent{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "system disk usage percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_disk_usage_percent{job=~\"$job\", instance=~\"$instance\", mountpoint=~\"/data\"}",
     "legendFormat": "{{instance}}:/data"
    }
   ]
  },
  {
   "title": "system network rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(system_network_bytes_sent_total{job=~\"$job\", instance=~\"$instance\", interface!~\"lo|docker.*|veth.*|br-.*\"}[1m]) > 1 * 1000 * 1000",
     "legendFormat": "{{instance}}:{{interface}}:sent"
    },
    {
     "expr": "rate(system_network_bytes_recv_total{job=~\"$job\", instance=~\"$instance\", interface!~\"lo|docker.*|veth.*|br-.*\"}[1m]) > 1 * 1000 * 1000",
     "legendFormat": "{{instance}}:{{interface}}:recv"
    }
   ]
  },
  {
   "title": "system gpu utilization percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpu_utilization_percent{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}:gpu{{gpu_index}}"
    }
   ]
  },
  {
   "title": "system gpu mem usage percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpu_memory_used_bytes{job=~\"$job\", instance=~\"$instance\"} / gpu_memory_total_bytes{job=~\"$job\", instance=~\"$instance\"} * 100",
     "legendFormat": "{{instance}}:gpu{{gpu_index}}"
    }
   ]
  },
  {
   "title": "process cpu usage percent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_cpu_percent{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "process mem rss",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_memory_rss_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "process gpu memory usage percent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpu_process_memory_bytes{job=~\"$job\", instance=~\"$instance\"} / gpu_memory_total_bytes{job=~\"$job\", instance=~\"$instance\"} * 100",
     "legendFormat": "{{instance}}:gpu{{gpu_index}}"
    }
   ]
  },
  {
   "title": "process gpu mem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gpu_process_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}:gpu{{gpu_index}}"
    }
   ]
  }
 ]
}