services:
  namesrv:
    image: apache/rocketmq:5.1.4
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./data/namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv
    environment:
      - JAVA_OPT_EXT=-Xms512m -Xmx512m -Xmn256m
    restart: unless-stopped

  broker:
    image: apache/rocketmq:5.1.4
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - ./data/broker/logs:/home/rocketmq/logs
      - ./data/broker/store:/home/rocketmq/store
      - ./broker.conf:/home/rocketmq/conf/broker.conf
    command: sh -c "export JAVA_OPT_EXT='-Xms1g -Xmx1g -Xmn512m' && sh mqbroker -c /home/rocketmq/conf/broker.conf"
    depends_on:
      - namesrv
    restart: unless-stopped

  dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rocketmq-dashboard
    ports:
      - 8080:8080
    environment:
      - NAMESRV_ADDR=namesrv:9876
    depends_on:
      - namesrv
      - broker
    restart: unless-stopped

  proxy:
    image: apache/rocketmq:5.1.4
    container_name: rmqproxy
    ports:
      - 8081:8080
    environment:
      - JAVA_OPT_EXT=-Drocketmq.namesrv.addr=namesrv:9876
    command: sh mqproxy
    depends_on:
      - namesrv
      - broker
    restart: unless-stopped

