# docker-compose.yml
services:
  cpp-dev-environment:
    build: .
    container_name: docker-client-24
    hostname: dev-container-24
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Linux 宿主机：直接挂载
      # - ~/workspace:/workspace
      # - ~/.ssh:/root/.ssh-host:ro
      # Windows 宿主机：注释上面，取消注释下面
      - D:\Coding:/workspace
      - C:\Users\Administrator\.ssh:/root/.ssh-host:ro
    ports:
      - "2224:22"      # SSH
    environment:
      - TZ=Asia/Shanghai
    working_dir: /workspace
    stdin_open: true
    tty: true
    restart: unless-stopped